services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db123
    ports:
      - "5433:5432"

  app:
    image: my-node-app
    ports:
      - "3000:3000"
