services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db123
    ports:
      - "5433:5432"

  app:
    depends_on:
      - db
    build: .
    ports:
      - "3000:3000"
